import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Luciana Serra</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.backgroundWrapper}>
				<Image className={styles.backgroundImage} alt="Imagem de fundo" src={'/main-background.webp'} fill />
			</div>
			<main className={styles.content}>
				<div className={styles.header}>
					<Link href="/">
						<Image
							src={'/header-logo.webp'}
							className={styles.logo}
							alt="Contorno de um passarinho"
							width="255"
							height="255"
						/>
					</Link>
					<div className={styles.nav}>
						<Link href="/">home</Link>
						<Link href="/">corporativa</Link>
						<Link href="/">social</Link>
						<Link href="/">fotojornalismo</Link>
						<Link href="/">bio</Link>
						<Link href="/">loja</Link>
						<Link href="/">contato</Link>
					</div>
				</div>
			</main>
		</>
	);
}
